project:
  type: website
  output-dir: docs


website:
  title: "Rural MN Migration Trends"
  navbar:
    left:
      - href: index.qmd
        text: Summary
      - lit_review.qmd
      - ipums_analysis.qmd
      - USPS_change_of_address.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true